######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 17 14:17:01 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tetrixboard.h tetrixpiece.h tetrixwindow.h
SOURCES += main.cpp tetrixboard.cpp tetrixpiece.cpp tetrixwindow.cpp
