######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 17 17:42:47 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += piecegenerator.h tetrixboard.h tetrixpiece.h tetrixwindow.h
SOURCES += main.cpp \
           piecegenerator.cpp \
           tetrixboard.cpp \
           tetrixpiece.cpp \
           tetrixwindow.cpp
