######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 18 18:27:44 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tetrixboard.h tetrixkey.h tetrixpiece.h tetrixwindow.h
SOURCES += main.cpp \
           tetrixboard.cpp \
           tetrixkey.cpp \
           tetrixpiece.cpp \
           tetrixwindow.cpp
